name: Weekly Trending Digest

on:
  schedule:
    # 07:00 UTC every Monday
    - cron:  '0 7 * * 1'
  workflow_dispatch:     # lets you run it manually from the UI

permissions:
  contents: write        # so the job can push commits

jobs:
  trending:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install deps
      run: pip install requests

    - name: Run digest script
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python tools/fetch_trending.py

    - name: Commit & push (if anything changed)
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add trending README.md || true
        if git diff --cached --quiet; then
          echo "No changes – nothing to commit."
        else
          git commit -m "chore: weekly trending digest"
          git push
        fi
